language: "ru"
theme : "advanced"
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: top
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - fullscreen
  - forecolor,backcolor
plugins:
  - fullscreen